### ISSUE TITLE
About the wav2vec2 model 

### ISSUE THREAD

**Issue by zhouyan19** [mt-upc/iwslt-2021#1]
![image](https://user-images.githubusercontent.com/57510806/186801845-96970247-1730-497d-857b-6412b941a59e.png)
In your paper you describe the wav2vec2 model you use, but I still don't know exactly which one is used. Is it "Wav2Vec 2.0 Large, 960 hours. Librispeech" in https://github.com/facebookresearch/fairseq/tree/main/examples/wav2vec ? Then what does "fine-tuned on psuedo-labels" mean? Thank you!

**Comment by zhouyan19** [comment]
oops, i did not read readme carefully

**Comment by gegallego** [comment]
Hi, no problem! Let us know if you have any other question 👍
