### ISSUE TITLE
ModuleNotFoundError: No module named 'augment'

### ISSUE THREAD

**Issue by Talgin** [mt-upc/iwslt-2021#5]
Hello! 

I'm facing this issue while running LNA-ED training command: 

CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 fairseq-hydra-train --config-dir ${IWSLT_ROOT}/config/ --config-name lna_ed.yaml

Would appreciate any help. Thanks!

**Comment by gegallego** [comment]
Hi @Talgin,

Thank you for using our code. Can you provide the whole error message? Have you installed `wavaugment`, as specified in [`environment.yml`](https://github.com/mt-upc/iwslt-2021/blob/main/environment.yml).

Best,
Gerard

**Comment by Talgin** [comment]
Hi @gegallego,

Sorry, my bad, I had problems with setting up the environment, so I think I missed this part. 
Installation of WavAugment solved the issue.

Thank you!
